version:  '3.5'
services:
  mysql-standalone:
    image:  mysql:5.6
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_ROOT=root
      - MYSQL_PASSWORD=Rr123
      - MYSQL_DATABASE=school
  api-rest:
    image: rodrigotenorio86/api-rest-devprojeto6
    container_name: api-rest-devprojeto6
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=root
      - DATABASE_NAME=school
      - DATABASE_PASSWORD=Rr123
      - DATABASE_PORT=3306
    command: sleep 200  
    depends_on:
      - mysql-standalone


